name: latihan_firebase1
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: 1.22.0
  flutter_speed_dial: ^6.0.0
  firebase_auth: 3.8.0
  cloud_firestore: 3.4.6
  firebase_storage: 10.3.8
  file_picker: 5.2.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

